### ISSUE TITLE
Probabilistic mapping 

### ISSUE THREAD

**Issue by jzheng84** [RoboJackets/igvc-software#241] opened 2017-09-24 21:50 UTC
The planner should be robust to erroneous points included in the point cloud from our sensors and mapping algorithm. The mapper should filter out these points based on the amount a point is added to a point cloud over the last x number of frames. If this is implemented correctly, false positives will be less of an issue for the line detector and pothole detector.

**Comment by dpattison3** [comment] 2018-01-07 23:44
I think we should move towards a true SLAM approach if we have time. There are a few libraries to consider:
https://github.com/OctoMap/octomap
https://github.com/ethz-asl/grid_map
https://github.com/CognitiveRobotics/omnimapper

**Comment by atuttle7** [comment] 2018-11-01 00:49
Should include a decay of some sort

**Comment by Alescontrela** [comment] 2019-02-09 17:58
Completed by Oswin. Still not merged into development branch, therefore not a bug

**Closed by Alescontrela** 2019-02-09 17:58 UTC
Labels: position mapping
