### ISSUE TITLE
Setup alias commands on Jessii NUCs to streamline operation

### ISSUE THREAD

**Issue by jzheng84** [RoboJackets/igvc-software#226] opened 2017-08-27 22:37 UTC
Example Freshman project:
"Test motors" alias that runs motors at a desired speed
"Test lidar" to start displaying what the lidar is perceiving

**Comment by JasonGibson274** [comment] 2017-08-28 22:26
to add along with this might be a quick reference of key commands since there is usually no mouse.

**Comment by Alescontrela** [comment] 2019-02-11 12:47
This can be accomplished using a combination of `rostopic echo` and rviz. Closing and putting on backlog, as it is not a bug.

**Closed by Alescontrela** 2019-02-11 12:47 UTC
Labels: testing
