### ISSUE TITLE
Localization issue while field testing 

### ISSUE THREAD

**Issue by Alescontrela** [RoboJackets/igvc-software#417] opened 2019-04-28 22:37 UTC
On the most recent testing day we observed a bug in our localization that resulted in inaccurate state estimates. This issue can no longer be reproduced running that same bag data on the most recent version of `devel` - 0cb80ff10ea666b424850d928c807bf38345b11c. 

Steps: 
```
# terminal 1
$ rosparam set /use_sim_time true; rosbag play JESSII_JOHNS_CREEK_2019-04-21-14-27-10.bag --pause --clock /velodyne_points:=/old1 /velodyne_packets:=/old2 /tf_static:=/old3 /tf:=/old4 /scan:=/old5 /odometry/gps:=/old6 /odometry/filtered:=/old7 /gps/filtered:=/old8 /accel/filtered:=/old9 /diagnostics:=/old10 /joy:=/old11 /initialpose:=/old12 /map:=/old13 /map_debug_pcl:=/old14 /mapper/empty_pc:=/old15 /mapper/ground:=/old16 /mapper/nonground:=/old17 /mapper/nonground_projected:=/old18 /move_base_simple/goal:=/old19 /odometry/filtered:=/old20 /vel:=/old21
# terminal 2 
$ roslaunch igvc_navigation localization.launch
# terminal 3 
$ roslaunch igvc_navigation robot_state_publisher.launch 
# terminal 4
$ rviz
```

**Comment by oswinso** [comment] 2019-05-05 00:23
Closing because no longer reproducible after recent testing.
> My best theory for what happened during testing day is this:
>
> 1) we noticed strange localization and modified localization.launch to fuse other sensors, amongst other things. 
> 2) we realized that the magnetometer’s gyro and heading values were flipped and fixed that, but didn’t revert localization to its original configuration.

**Closed by oswinso** 2019-05-05 00:23 UTC
